### ISSUE TITLE
RoR group project: set up your Kanban board

### ISSUE THREAD

**Issue by Nahid1911** [Nahid1911/RecipeApp-RoR#17]
We are 2 members in this capstone
@bronnie313 : Bisaso Ronald
@Nahid1911 : Nahid Raihan

This is our project [link](https://github.com/Nahid1911/RecipeApp-RoR/projects/1)

**Comment by FrederickMih** [comment]
## Hi :raising_hand: :raising_hand: @Team, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!



<img src="https://media.giphy.com/media/r5eafWP6dcbxX8cLeN/giphy.gif"  width ="150"><img>

## Highlights :green_circle: 

- Each card is correctly assigned to each team member :+1: 


## Required Changes ♻️

- [ ] Hi Team, kindly check once more the [requirements of this project](https://github.com/microverseinc/curriculum-rails/blob/main/recipe-app/buisness_requirements.md#project-requirements) . Each requirement should have at least one corresponding card in the Kanban board. Kindly make sure the list of the given requirements are found in your cards

_Check the comments under the review._

## Optional suggestions
**N/A**
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._



Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by TedLivist** [comment]
## STATUS: APPROVED ✔️ ✔️

Hi @Nahid1911 and @bronnie313,

✔️ Tasks are well assigned

Your project is complete!  There is nothing else to say other than... it's time to go ahead with the project :shipit: 
Congratulations! 🎉

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the Issue thread if something is not 100% clear. And please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
